autoservisas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index_nm'),
    path('autos/', views.get_autos, name='autos-all'),
    path('autos/<int:auto_id>', views.get_one_auto, name='auto-one'),
    path('orders/', views.UzsakymasListView.as_view(), name='orders-all'),
    path('orders/<int:pk>', views.UzsakymasDetailView.as_view(), name='order-one'),
    path('search/', views.search, name='search_nm'),
    path('myorders/', views.OrdersByUserListView.as_view(), name='my-orders'),
    path('register/', views.register_user, name='register'),
    path('profile/', views.get_user_profile, name='user-profile'),

]

mainproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('autoservisas/', include('autoservisas.urls')),  # autoservisas.urls folderis.failas
    path('', RedirectView.as_view(url='autoservisas/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tinymce/', include('tinymce.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# homepage/admin
# homepage/autoservisas
# homepage -> /autoservisas redirektas(nukreipimas)

autoservisas/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
from PIL import Image
from tinymce.models import HTMLField


class Gamintojas(models.Model):
    pavadinimas = models.CharField('Gamintojo pavadinimas', max_length=20)

    def __str__(self):
        return f'{self.pavadinimas}'

    class Meta:
        verbose_name = "Gamintojas"
        verbose_name_plural = "Gamintojai"


class Modelis(models.Model):
    pavadinimas = models.CharField('Modelio pavadinimas', max_length=20, help_text="Iveskite automobilio modelius")
    gamintojas = models.ForeignKey(Gamintojas, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return f'{self.pavadinimas}'

    class Meta:
        verbose_name = "Modelis"
        verbose_name_plural = "Modeliai"


class Klientas(models.Model):
    vardas = models.CharField('Vardas', max_length=20)
    pavarde = models.CharField('Pavarde', max_length=20)
    tel_numeris = models.CharField('Telefono numeris', max_length=9)

    def __str__(self):
        return f'{self.pavarde} {self.vardas} {self.tel_numeris}'

    class Meta:
        ordering = ('pavarde', 'vardas')
        verbose_name = "Klientas"
        verbose_name_plural = "Klientai"


class Masina(models.Model):
    reg_numeris = models.CharField('Registracijos numeris', max_length=6, unique=True)
    modelis = models.ForeignKey(Modelis, on_delete=models.CASCADE)
    klientas = models.ForeignKey(Klientas, on_delete=models.CASCADE)
    vin_kodas = models.CharField('VIN kodas', max_length=17, unique=True, default='Cia turi buti unikalus kodas')
    cover = models.ImageField('Nuotrauka', upload_to='photos', null=True, blank=True)
    aprasymas = HTMLField(null=True, blank=True)

    def __str__(self):
        return f'{self.reg_numeris}'

    class Meta:
        verbose_name = "Automobilis"
        verbose_name_plural = "Automobiliai"


class Paslauga(models.Model):
    pavadinimas = models.CharField('Pavadinimas', max_length=50)
    kaina = models.DecimalField('Kaina', max_digits=7, decimal_places=2)

    def __str__(self):
        return f'{self.pavadinimas}'

    class Meta:
        verbose_name = "Paslauga"
        verbose_name_plural = "Paslaugos"


class Uzsakymas(models.Model):
    masina = models.ForeignKey(Masina, on_delete=models.CASCADE)
    # pilna_kaina = models.DecimalField('Pilna kaina', max_digits=8, decimal_places=2, null=True, blank=True)
    date = models.DateField(auto_now_add=True)
    uzsakovas = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    grazinimo_terminas = models.DateField('Grazinimo terminas', null=True, blank=True)

    UZSAKYMO_STATUS = (
        ('p', 'Priimtas'),
        ('v', 'Vykdomas'),
        ('a', 'Atliktas'),
    )

    statusas = models.CharField(
        'Statusas',
        max_length=1,
        choices=UZSAKYMO_STATUS,
        default='p',
        blank=True,
        help_text='Uzsakymo statusas'
    )

    @property
    def yra_pradelstas(self):
        if self.grazinimo_terminas and date.today() > self.grazinimo_terminas:
            return True
        else:
            return False

    @property
    def skaiciuoti_pilna_kaina(self):
        suma = 0
        for eilute in self.uzsakymoeilute_set.all():
            suma += eilute.skaiciuoti_paslaugu_kaina
        return suma

    def __str__(self):
        return f"{self.statusas} {self.masina} {self.date}, kaina: {self.skaiciuoti_pilna_kaina}"

    class Meta:
        verbose_name = "Uzsakymas"
        verbose_name_plural = "Uzsakymai"


class UzsakymoEilute(models.Model):
    uzsakymas = models.ForeignKey(Uzsakymas, on_delete=models.CASCADE)
    kiekis = models.PositiveIntegerField('Kiekis')
    paslauga = models.ForeignKey(Paslauga, on_delete=models.CASCADE)
    # paslaugu_kaina = models.DecimalField('Paslaugu kaina', max_digits=7, decimal_places=2, null=True, blank=True)

    @property
    def skaiciuoti_paslaugu_kaina(self):
        res = self.paslauga.kaina * self.kiekis
        return res

    def __str__(self):
        return f"{self.paslauga}"

    class Meta:
        verbose_name = "Uzsakymo eilute"
        verbose_name_plural = "Uzsakymo eilutes"


class UzsakymasReview(models.Model):
    date_created = models.DateTimeField(auto_now_add=True)
    content = models.TextField('Komentaras', max_length=1000)
    uzsakymas = models.ForeignKey(Uzsakymas, on_delete=models.CASCADE, blank=True)
    reviewer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f'{self.date_created}, {self.reviewer}, {self.uzsakymas}, {self.content}'


class Profile(models.Model):
    picture = models.ImageField(upload_to='profile_pics', default='default-profile.png')
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user.username} profilis'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.picture.path:
            img = Image.open(self.picture.path)
            thumb_size = (150, 150)
            img.thumbnail(thumb_size)
            img.save(self.picture.path)

autoservisas/forms.py
from django import forms
from .models import UzsakymasReview, Profile, User


class UzsakymasReviewForm(forms.ModelForm):
    class Meta:
        model = UzsakymasReview
        fields = ('content', 'uzsakymas', 'reviewer')
        widgets = {
            'uzsakymas': forms.HiddenInput(),
            'reviewer': forms.HiddenInput()
        }


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('picture',)


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email',)

autoservisas/views.py
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.views import generic
from django.db.models import Q
from django.core.paginator import Paginator
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.decorators import login_required

from .models import Paslauga, Uzsakymas, Masina, User, Modelis, Gamintojas, UzsakymoEilute, Klientas
from .forms import UzsakymasReviewForm, ProfileUpdateForm, UserUpdateForm
from .utils import check_pasword


def index(request):
    paslaugu_kiekis = Paslauga.objects.count()
    visu_uzsakymu_kiekis = Uzsakymas.objects.count()
    atliktu_uzsakymu_kiekis = Uzsakymas.objects.filter(statusas__exact='a').count()
    automobiliu_kiekis = Masina.objects.count()

    num_visits = request.session.get('num_visits', 1)
    request.session['num_visits'] = num_visits + 1

    context = {
        'paslaugu_kiekis': paslaugu_kiekis,
        'visu_uzsakymu_kiekis': visu_uzsakymu_kiekis,
        'atliktu_uzsakymu_kiekis': atliktu_uzsakymu_kiekis,
        'automobiliu_kiekis': automobiliu_kiekis,
        'num_visits': num_visits
    }

    return render(request, 'index.html', context=context)


def get_autos(request):
    autos = Masina.objects.all()
    paginator = Paginator(autos, 8)
    page_number = request.GET.get('page')
    paged_autos = paginator.get_page(page_number)
    context = {'autos': paged_autos}
    return render(request, 'autos.html', context=context)


def get_one_auto(request, auto_id):
    one_auto = get_object_or_404(Masina, pk=auto_id)
    context = {'one_auto': one_auto}
    return render(request, 'auto.html', context=context)


class UzsakymasListView(generic.ListView):
    model = Uzsakymas
    context_object_name = 'uzsakymas_list'
    template_name = 'orders.html'
    paginate_by = 5


class UzsakymasDetailView(generic.edit.FormMixin, generic.DetailView):
    model = Uzsakymas
    context_object_name = 'uzsakymas'
    template_name = 'order.html'
    form_class = UzsakymasReviewForm

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        self.uzsakymas_object = self.get_object()
        form.instance.uzsakymas = self.uzsakymas_object
        form.instance.reviewer = self.request.user
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('order-one', kwargs={'pk': self.uzsakymas_object.id})


def search(request):
    query_text = request.GET.get('search_text')
    # https://docs.djangoproject.com/en/4.2/ref/models/lookups/
    search_results = Masina.objects.filter(
        Q(klientas__pavarde__icontains=query_text) |
        Q(modelis__pavadinimas__icontains=query_text) |
        Q(modelis__gamintojas__pavadinimas__icontains=query_text) |
        Q(reg_numeris__icontains=query_text) |
        Q(vin_kodas__icontains=query_text)
    )

    context = {'query_text': query_text,
               'masina_list': search_results}

    return render(request, 'search_results.html', context=context)


class OrdersByUserListView(LoginRequiredMixin, generic.ListView):
    model = Uzsakymas
    context_object_name = 'uzsakymas_list'
    template_name = 'user_orders.html'

    def get_queryset(self):
        return Uzsakymas.objects.filter(uzsakovas=self.request.user)


@csrf_protect
def register_user(request):
    if request.method == 'GET':
        return render(request, 'registration/registration.html')

    elif request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        password2 = request.POST.get('password2')

        if not check_pasword(password):
            messages.error(request, 'Slaptažodis, mažiausiai 8 simboliai!!!')
            return redirect('register')

        if password != password2:
            messages.error(request, 'Slaptažodžiai nesutampa')
            return redirect('register')

        if User.objects.filter(username=username).exists():
            messages.error(request, f'Vartotojo vardas {username} jau egzistuoja')
            return redirect('register')

        if User.objects.filter(email=email).exists():
            messages.error(request, f'Email {email} jau egzistuoja')
            return redirect('register')

        User.objects.create_user(username=username, email=email, password=password)
        messages.info(request, f'Vartotojas {username} sėkmingai užregistruotas!')
        return redirect('login')


@login_required
@csrf_protect
def get_user_profile(request):
    if request.method == 'POST':
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        u_form = UserUpdateForm(request.POST, instance=request.user)

        if p_form.is_valid() and u_form.is_valid():
            p_form.save()
            u_form.save()
            messages.info(request, "Profilis atnaujintas")
        else:
            messages.error(request, "Profilis neatnaujintas")
        return redirect('user-profile')

    p_form = ProfileUpdateForm(instance=request.user.profile)
    u_form = UserUpdateForm(instance=request.user)

    context = {
        'p_form': p_form,
        'u_form': u_form
    }

    return render(request, 'profile.html', context=context)

autoservisas/templates/auto.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Automobilis</h1>

{% if one_auto.cover %}
    <img src="{{ one_auto.cover.url }}" style="width: 40%;" class="img-fluid"/>
{% else %}
    <img src="{% static 'img/no-image.png' %}" style="width: 40%;" class="img-fluid"/>
{% endif %}

<h4>Savininkas: {{ one_auto.klientas }}</h4>
<h4>Gamintojas: {{ one_auto.modelis.gamintojas }}</h4>
<h4>Modelis: {{ one_auto.modelis }}</h4>
<h4>Registracijos numeris: {{ one_auto.reg_numeris }}</h4>
<h4>VIN kodas: {{ one_auto.vin_kodas }}</h4>
<h4>Aprašymas: {{ one_auto.aprasymas | safe }}</h4>

{% endblock %}
{% block title %}<title>{{ one_auto.reg_numeris }}</title>{% endblock %}

autoservisas/templates/autos.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1>Automobiliai</h1>
<p>Visi servise užregistruoti automobiliai:</p>
<div class="row">
    {% for auto_obj in autos %}
        <div class="col-sm-6 col-md-3 d-flex align-items-stretch">
            <div class="card mb-4 shadow">
        {% if auto_obj.cover %}
            <img class="card-img-top" src="{{ auto_obj.cover.url }}"/>
        {% else %}
            <img class="card-img-top" src="{% static 'img/no-image.png' %}"/>
        {% endif %}
        <div class="card-body">
                    <h6 class="card-subtitle mb-2 text-muted">{{ auto_obj.modelis }}</h6>
                    <p class="card-text"><a href="{% url 'auto-one' auto_obj.id %}">{{ auto_obj.reg_numeris }}</a></p>
                </div>
           </div>
        </div>
    {% endfor %}
</div>

{% if autos.has_other_pages %}
    <ul class="pagination pagination-sm">
        {% for nr in autos.paginator.page_range %}
            {% if autos.number == nr %}
                <li class="page-item active">
                    <a class="page-link">{{ nr }}</a>
                </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" href="?page={{ nr }}">{{ nr }}</a>
            </li>
            {% endif %}
        {% endfor %}
    </ul>
{% endif %}
{% endblock %}

autoservisas/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block title %}
    <title>Klaipėdos autoservisas</title>
    {% endblock %}
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
      integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <!-- Add additional CSS in static file -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
  </head>
  <body>
    <!-- Navigation -->

    <nav
      class="navbar navbar-expand-lg navbar-light bg-light static-top mb-5 shadow"
    >
      <div class="container">
        <a class="navbar-brand" href="{% url 'index_nm' %}">
          <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor"
               class="bi bi-taxi-front" viewBox="0 0 16 16">
              <path d="M4.862 5.276 3.906 7.19a.51.51 0 0 0
              .497.731c.91-.073 2.35-.17 3.597-.17s2.688.097 3.597.17a.51.51 0 0 0
              .497-.731l-.956-1.913A.5.5 0 0 0 10.691 5H5.309a.5.5 0 0 0-.447.276M4 10a1 1 0 1 1-2 0 1 1 0 0 1 2
              0m10 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0m-9 0a1 1 0 0 1 1-1h4a1 1 0 1 1 0 2H6a1 1 0 0 1-1-1"/>
              <path d="M6 1a1 1 0 0 0-1 1v1h-.181A2.5 2.5 0 0 0 2.52 4.515l-.792
              1.848a.8.8 0 0 1-.38.404c-.5.25-.855.715-.965 1.262L.05 9.708a2.5 2.5 0 0 0-.049.49v.413c0 .814.39 1.543
              1 1.997V14.5a.5.5 0 0 0 .5.5h2a.5.5 0 0 0 .5-.5v-1.338c1.292.048 2.745.088 4
              .088s2.708-.04 4-.088V14.5a.5.5 0 0 0 .5.5h2a.5.5 0 0 0 .5-.5v-1.892c.61-.454 1-1.183
              1-1.997v-.413q0-.248-.049-.49l-.335-1.68a1.8 1.8 0 0 0-.964-1.261.8.8 0 0 1-.381-.404l-.792-1.848A2.5 2.5
              0 0 0 11.181 3H11V2a1 1 0 0 0-1-1zM4.819 4h6.362a1.5 1.5 0 0 1 1.379.91l.792 1.847a1.8 1.8 0 0 0
              .853.904c.222.112.381.32.43.564l.336 1.679q.03.146.029.294v.413a1.48 1.48 0 0 1-1.408
              1.484c-1.555.07-3.786.155-5.592.155s-4.037-.084-5.592-.155A1.48 1.48 0 0 1 1
              10.611v-.413q0-.148.03-.294l.335-1.68a.8.8 0 0 1 .43-.563c.383-.19.685-.511.853-.904l.792-1.848A1.5 1.5 0
              0 1 4.82 4Z"/>
          </svg>
          Klaipėdos autoservisas!</a
        >
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user-profile' %}">
                 <svg class="bi bi-person"
                         width="1.5em"
                         height="1.5em"
                         viewBox="0 0 16 16"
                         fill="currentColor"
                         xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1
                            1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168
                            1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8
                            7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z" clip-rule="evenodd"/>
                 </svg>
                 {{ user.username }}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'my-orders' %}">Mano užsakymai</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}?next={{ request.path }}">Prisijungti</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'register' %}?next={{ request.path }}">Registruotis</a>
            </li>
          {% endif %}

            <li class="nav-item">
              <a class="nav-link" href="{% url 'index_nm' %}">Pradžia</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'autos-all' %}">Automobiliai</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'orders-all' %}">Užsakymai</a>
            </li>
          </ul>

          <form
            class="form-inline my-2 my-lg-0"
            action="{% url 'search_nm' %}"
            method="get"
          >
            <input
              class="form-control mr-sm-2"
              type="search"
              placeholder="Paieška"
              aria-label="Search"
              name="search_text"
            />
            <button class="btn btn-outline-info my-2 my-sm-0" type="submit">
              Ieškoti
            </button>
          </form>
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <form method="post" action="{% url 'logout' %}">
              {% csrf_token %}
              <button type="submit" class="logout-button">Atsijungti</button>
            </form>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
      {% for message in messages %}
      <div class="alert {% if message.tags == 'error' %} alert-danger
                      {% else %} alert-success
                      {% endif %}"
         role="alert">
        {{ message }}
      </div>
      {% endfor %}
    <div class="container">{% block content %}{% endblock %}</div>

    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
      integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
      integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

autoservisas/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Klaipėdos autoservisas</h1>
<h2>Statistika:</h2>
<p>Paslaugu kiekis: {{ paslaugu_kiekis }}</p>
<p>Visu uzsakymu kiekis: {{ visu_uzsakymu_kiekis }}</p>
<p>Atliktu uzsakymu kiekis: {{ atliktu_uzsakymu_kiekis }}</p>
<p>Automobiliu kiekis: {{ automobiliu_kiekis }}</p>
{% if user.username %}
    <p>Sveiki, {{ user.username }}</p>
{% else %}
    <p>Sveiki, svecias</p>
{% endif %}
<p>Jus lankotes {{ num_visits }} karta</p>
{% endblock %}

autoservisas/templates/order.html
{% extends 'base.html' %}

{% block content %}
    <h1>Užsakymo informacija</h1>

    <table class="table">
     <tbody>
        <tr>
            <th>Data:</th>
            <td>{{ uzsakymas.date }}</td>
        </tr>
        <tr>
            <th>Statusas:</th>
            <td>
                {% if uzsakymas.statusas == 'p' %}
                    Priimtas
                {% elif uzsakymas.statusas == 'v' %}
                    Vykdomas
                {% else %}
                    Atliktas
                {% endif %}
            </td>
        </tr>
        <tr>
            <th>Automobilis:</th>
            <td>{{ uzsakymas.masina.reg_numeris }} {{ uzsakymas.masina.modelis }}</td>
        </tr>
        <tr>
            <th>Klientas:</th>
            <td>{{ uzsakymas.masina.klientas.vardas }} {{ uzsakymas.masina.klientas.pavarde }}
                {{ uzsakymas.masina.klientas.tel_numeris }}
            </td>
        </tr>
        <tr>
            <th>VIN kodas:</th>
            <td>{{ uzsakymas.masina.vin_kodas }}</td>
        </tr>
     </tbody>
    </table>

    <div class="mt-4">
        <h2>Mokėjimo informacija</h2>
        <table class="table">
                <tr>
                    <th>Paslauga</th>
                    <th>Kiekis</th>
                    <th>Kaina</th>
                    <th>Suma</th>
                </tr>
            <tbody>
                {% for eilute in uzsakymas.uzsakymoeilute_set.all %}
                    <tr>
                        <td>{{ eilute.paslauga.pavadinimas }}</td>
                        <td>{{ eilute.kiekis }}</td>
                        <td>{{ eilute.paslauga.kaina }} &euro;</td>
                        <td>{{ eilute.skaiciuoti_paslaugu_kaina }} &euro;</td>
                    </tr>
                {% endfor %}
                <tr>
                  <td colspan="3" style="text-align: right; font-weight: bold;">Iš viso:</td>
                  <td>{{ uzsakymas.skaiciuoti_pilna_kaina }} &euro;</td>
                </tr>
            </tbody>
        </table>
    </div>
                <hr/>
                {% if user.is_authenticated %}
                        <div><h5>Palikite komentarą apie užsakymą:</h5>
                        <form method="post">
                        {% csrf_token %}
                        {{ form.content }}<div>
                    <input type="submit" class="btn btn-outline-success btn-sm" value="Išsaugoti komentarą"/>
                </div>
                </form>
                </div>
                {% endif %}
                <hr/>
                {% for uzsakymasreview in uzsakymas.uzsakymasreview_set.all %}
                    <small><b>{{ uzsakymasreview.reviewer }}</b> <em>{{ uzsakymasreview.date_created }}</em></small>
                    <p class="bg-light">{{ uzsakymasreview.content }}</p>
                <hr/>
                {% endfor %}
                {% if not uzsakymas.uzsakymasreview_set.first %}
                    <p>Užsakymas komentarų neturi!</p>
                <hr/>
                {% endif %}
{% endblock %}

autoservisas/templates/user_orders.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ user }}</h1>
<img class="rounded-circle" src="{{ user.profile.picture.url }}" width="50px" height="50px"/>
<p>Mano turimi užsakymai:</p>
{% if uzsakymas_list %}
<ul>
    {% for uzsakymas in uzsakymas_list %}
        <li>
            {{ uzsakymas.id }}
            <p><a href="{% url 'order-one' uzsakymas.masina.id %}">{{ uzsakymas.masina }}</a></p>
            <p class="{% if uzsakymas.yra_pradelstas %}text-danger">
            {% else %}text-success">
            {% endif %} {{ uzsakymas.grazinimo_terminas }} {{ uzsakymas.get_statusas_display }}</p>
        </li>
    {% endfor %}
</ul>
{% else %}
<p>Jūs neturite užsakymų!</p>
{% endif %}
{% endblock %}